#! /bin/sh

# https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html

case "$1" in
  start)
    echo "Starting AESD socket server"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping AESD socket server"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0